### PR TITLE
Change pager scrolling behaviour, Fixes #562

### LINKED ISSUE #562: Really strange scrolling issue when paging with firefox
Sometimes `scrollTo(0,0)` does not work in firefox. This is really strange and I cannot even reproduce this all the time, but enough to be really annoying :D

Steps to reproduce
1) with "default demo products" change the pagesize to 3 (easier to get pager)
2) go to "art" category (it should have three pages as the pagesize is small)
3) scroll a bit to see the pager (important, also it seems that the viewport size also affects this a bit)
4) change page
=> https://github.com/PrestaShop/hummingbird/blob/986d1a2f7f67bc865774b9500b18051160932ffe/src/js/modules/facetedsearch/update.ts#L102 tries to scroll to top but it doesn't always happen (no errors, nothing).

It looks like firefox gets confused when the content changes and it doesn't always understand that it should scroll.. (also tried adding a small delay with `setTimeout` but that didn't seem to work either)

I can force it to work consistently by adding `window.scrollTo(0,1)` before the `window.scrollTo(0,0)` but that seems wrong.

This does not seem to ever happen with chrome.

As a side not the scrolling should probably happen to be at the top of `<div id="products">` so that for mobile users the products are shown even if the header is tall.. In place of window.scrollTo(0,0) should be something like

```js
document.getElementById('products').scrollIntoView(true); 
```

and as we have a fixed header give it some scroll margin

```css
section#products {
  scroll-margin-top: 150px; /* really the height of header */
}
```

In my opinion the scroll-margin-top should be set so that in desktop view the text "There are 8 products" is still visible and in mobile view filters and sort order are still visible

### PR DESCRIPTION
**Pull request by tswfi**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Change how pager links scroll back to top of the product list. Also remove scrolling when changing facets
| Type?             | improvement
| BC breaks?        | no (maybe? one class changed?)
| Deprecations?     | no
| Fixed ticket?     | Fixes #562
| Sponsor company   | 
| How to test?      | Change facet filters => should not scroll so you can easily select other facets too. Use pager in product listing => should scroll to top (pretty consistently even with firefox)

### CODE REVIEW

**Review by tleon — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

File: src/js/modules/facetedsearch/update.ts [hunk 1]
```diff
@@ -80,6 +80,18 @@ export default () => {
     );
   });
 
+  /**
+   * Pager links also scroll up
+   */
+  $('body').on('click', Theme.selectors.listing.pagerLink, (event) => {
+    event.preventDefault();
+    document.getElementById('js-product-list-top')?.scrollIntoView({block: 'start', behavior: 'auto'});
```
Comment (SharakPL) [inline src/js/modules/facetedsearch/update.ts:88]: Maybe use here `Theme.selectors.listing.listTop`

Comment (tswfi) [reply src/js/modules/facetedsearch/update.ts:88]:
```
src/js/constants/selectors-map.ts:  listTop: '#js-product-list-top',
```
Those are in jQuery format.. should there be a `listTopId: 'js-product-list-top'`

Comment (tswfi) [reply src/js/modules/facetedsearch/update.ts:88]: Or 

```diff
--- a/src/js/modules/facetedsearch/update.ts
+++ b/src/js/modules/facetedsearch/update.ts
@@ -85,7 +85,8 @@ export default () => {
    */
   $('body').on('click', Theme.selectors.listing.pagerLink, (event) => {
     event.preventDefault();
-    document.getElementById('js-product-list-top')?.scrollIntoView({block: 'start', behavior: 'auto'});
+    /* selectors are in jQuery format, slice the leading # character out */
+    document.getElementById(Theme.selectors.listing.listTop.slice(1))?.scrollIntoView({block: 'start', behavior: 'auto'});
     prestashop.emit(
       events.updateFacets,
       $(event.target)?.closest('a')?.get(0)?.getAttribute('href'),
```

but this feels a bit dirty..

Comment (SharakPL) [reply src/js/modules/facetedsearch/update.ts:88]: > ```
> src/js/constants/selectors-map.ts:  listTop: '#js-product-list-top',
> ```
> 
> Those are in jQuery format.. should there be a `listTopId: 'js-product-list-top'`

Well, first of all I'm not sure it should even be an ID. Any `js-...` selector should be a class.

And what do you mean by _jQuery format_? They are simple selectors :)
Just use `document.querySelector(Theme.selectors.listing.listTop)` instead of `document.getElementById('js-product-list-top')`

Comment (tswfi) [reply src/js/modules/facetedsearch/update.ts:88]: well, css selector (where `#` denotes id) which jQuery uses everywhere..

vanilla js getElementById takes only the id not the css selector. 

getElementById is faster than querySelector (not by much but it is by definition).

I'll change it to use querySelector

Comment (SharakPL) [reply src/js/modules/facetedsearch/update.ts]: Some say [querySelector is faster](https://www.reddit.com/r/learnjavascript/comments/i0f5o8/performance_of_getelementbyid_vs_queryselector/?rdt=42342) 😉 Doesn't matter nowadays really, but just for consistency we should use `querySelector` and `querySelectorAll`. Especially since we're using selectors-map.

Comment (tswfi) [reply src/js/modules/facetedsearch/update.ts]: yup, it was changed here [4a29900](https://github.com/PrestaShop/hummingbird/pull/565/commits/4a299009dbe9758aa6a5da22a65f2921bc252f14)

**Review by SharakPL — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @tswfi ,

I have 2 different behaviors with your PR.

With Firefox, when changing/using filter, _**it doesn't scroll back to the top**_. So the customer can filter multiple attributes at the same time.

https://github.com/PrestaShop/hummingbird/assets/16019289/12716e64-5f7b-4abc-a573-d5ea8b373558

On Chrome, _**it always scrolls to the top**_. 

https://github.com/PrestaShop/hummingbird/assets/16019289/5caafa33-c62c-46aa-b86a-dfeedc5241fa

The behavior should be consistent of both browsers. It should be like Firefox.
I have `npm run build` before testing on both browsers.

Could you check ? ^^
Thanks!

**Comment by tswfi** [comment]
Cannot replicate on OSX chrome, did you also clear your browser cache (or force refresh)?

image

https://github.com/PrestaShop/hummingbird/assets/1352132/ede217de-d3c5-4563-ae0a-6ccf456990e2

There are some minor "jumps" as new things are added to the page (like the "remove this filtering facet" buttons above the products and "clear all" button above the facets, but those are outside of the scope).

**Comment by florine2623** [comment]
Yes, i have updated my chrome to version 120.0.6099.129, empty cache and hard reload 🤔 

Maybe another @PrestaShop/qa-functional could test it. In any case, it works well with Firefox. It just needs to be checked one more time on Chrome.

**Comment by SharakPL** [comment]
TBH I never liked filters in the left column. It's too messed up. Would be much better to move it on top of the products list in the center column and categories block to the top.

**Comment by tswfi** [comment]
> TBH I've never liked filters in the left column. It's too messed up. Would be much better to move it on top of the products list in the center column and categories block to the top.

A setting would be the best.. Some merchants have lots of filters and having them on top of the products is not that easy to style nicely. Preferably there should be at least three different ways to show the filters. 1) like now 2) above the products 3) as a "sliding panel" from a button

Anyway, changing the logic is out of scope for this pull request.

**Comment by AureRita** [comment]
Hi @tswfi 

Thank you for your PR, I tested it and it seems to works in my case as you can see : 

[recording(80).webm](https://github.com/PrestaShop/hummingbird/assets/100699445/20e63efd-9393-450d-ae5c-9184aa87dd96)

Tested on develop and 8.1.x.
Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Review by AureRita — APPROVED** [review]
