### PR TITLE
Handle line breaks in comment content display

### LINKED ISSUE #868: [BUG] productcomments does not display text in correct formatting, line breaks are missing
### Prerequisites

- [x] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [x] I have already [searched in existing issues](https://github.com/PrestaShop/hummingbird/issues?q=is%3Aissue+type%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hi
I did some tests and I saw that on the product page, the line breaks are not shown as they are in the database table, so there is only a display problem

Image
Image

I've used this text

`bel prodotto

khgvlkjbpòlkèè++

3724w6£&%&/)?=ààè+++

6899'ìàù`

but then everything is shown on one line

bye

### Expected behavior

_No response_

### Steps to reproduce

add a comment in the product page

### PrestaShop version(s) where the bug happened

2.0.0

### PHP version(s) where the bug happened

8.1

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by tblivet**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Handle line breaks in comment content display
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/hummingbird/issues/868
| Sponsor company   | @PrestaShopCorp
| How to test?      | Check the issue https://github.com/PrestaShop/hummingbird/issues/868

### CODE REVIEW

File: src/js/modules/productcomments.ts [hunk 1]
```diff
@@ -480,6 +480,17 @@ class ProductCommentsListing {
...
 
+  private static formatCommentContent(content: string): string {
+    if (!content) return '';
+
+    const div = document.createElement('div');
+    div.textContent = content;
+    const commentContent = div.innerHTML;
+
+    // Convert line breaks to <br> tags
+    return commentContent.replace(/\r\n/g, '<br>').replace(/\n/g, '<br>').replace(/\r/g, '<br>');
```
Comment (ga-devfront) [inline src/js/modules/productcomments.ts]:
```suggestion
    return div.innerHTML.replace(/\r\n|\r|\n/g, '<br>');
```

**Review by ga-devfront — DISMISSED** [review]

**Review by ga-devfront — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @tblivet 

Thank you for your PR, I tested it and it seems to works as you can see : 

Capture d’écran du 2025-12-18 17-01-28


Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.
